### ISSUE TITLE
Improve readme.md

### ISSUE THREAD

**Issue by hritikksingh** [hritikksingh/Twitter-video-emotion-and-sentiment-analysis#1]
Make enhancements in readme.md with more details about the workflow of the project.

**Comment by pratyush2303** [comment]
Hey hritikk, can you please assign me this issue. I will make a proper and brief documentation for this project. I will contain all details of all files used.

**Comment by hritikksingh** [comment]
@pratyush2303 go ahead.

**Comment by HarshKumarChoudary** [comment]
Please consider me next in the queue if the issue is not resolved. I'm a GSSOC22 participant

**Comment by pratyush2303** [comment]
I am almost done with this issue. In just one day I'll be ready.
