### ISSUE TITLE
OpenSourceContribution

### ISSUE THREAD

**Issue by debamitr1012** [hritikksingh/Twitter-video-emotion-and-sentiment-analysis#11]
I want to contribute in this project... please tell me what to do. You can whatsapp me at +91 9836578565
Thank You.

**Comment by hritikksingh** [comment]
I would suggest first fork and clone it and try to run the code before you think of any new functionality so that you can see what are the current dependency and workflow

**Comment by debamitr1012** [comment]
can you please provide with the dataset link

**Comment by hritikksingh** [comment]
> can you please provide with the dataset link

I have already created models based on data from kaggle.
If you want dataset for training models then I would suggest please try for a better model and let us know so that we can merge that too.

**Comment by hritikksingh** [comment]
RAVDESS and 12 emotion tweet analysis.
Type these two and you will get the datasets.

**Comment by debamitr1012** [comment]
ok thank you
and one more thing i will update in my own forked repo or in your repo i will create pull requests?

**Comment by hritikksingh** [comment]
It depends on you, if you want your contribution to be recognised under GSSoC then create a PR to my repo.

**Comment by debamitr1012** [comment]
Ok sure
