### ISSUE TITLE
Remove __pycache__

### ISSUE THREAD

**Issue by anandxkumar** [hritikksingh/Twitter-video-emotion-and-sentiment-analysis#18]
To keep the codebase clean, it is suggested to remove all cache folders, so `__pycache__` should be deleted and a `.gitignore` file should be created and the `**/__pycache__/` directory should be added to avoid sending all `__pycache__` to the repository. 

**Note**: Make sure to first delete all cache before writing `.gitignore`.

**Comment by hritikksingh** [comment]
> To keep the codebase clean, it is suggested to remove all cache folders, so `__pycache__` should be deleted and a `.gitignore` file should be created and the `**/__pycache__/` directory should be added to avoid sending all `__pycache__` to the repository. 
> 
> **Note**: Make sure to first delete all cache before writing `.gitignore`.
> 
> 
> 
> 

Yeah, that was my mistake.
Thanks for pointing out :)
