### ISSUE TITLE
Better Speech analysis

### ISSUE THREAD

**Issue by hritikksingh** [hritikksingh/Twitter-video-emotion-and-sentiment-analysis#6]
We are splitting the video into 2 parts, one is text and the other is the frequency of the person's voice.
We are analyzing both of them separately using different Neural network models.
In this issue, we want to enhance the Text analysis of the speech of the video.
Requires knowledge of:
- Python
- Machine Learning
- NLP
- Neural Networks

**Comment by Pushpita05** [comment]
Hey I would like to contribute to this porject. Could you elaborate this issue

**Comment by hritikksingh** [comment]
> Hey I would like to contribute to this porject. Could you elaborate this issue

Hey @Pushpita05, in this issue you have to enhance the sentiment analysis of text.
The speech will be converted to text and your work is to make a NN model to analyse that text sentiments.

**Comment by Pushpita05** [comment]
Sure. I would love to work on it

**Comment by hritikksingh** [comment]
@Pushpita05 I have assigned it to you.
Happy learning.

**Comment by aritra1804** [comment]
Thanks,Can ik the deadline

**Comment by Pushpita05** [comment]
Thanks. Could you please let me know the deadline of this issue

**Comment by hritikksingh** [comment]
10 days would be sufficient

**Comment by Venkatakrishnan-Ramesh** [comment]
Hey i would also like to work on the tweet analysis of the text which will be generated from video

**Comment by hritikksingh** [comment]
> Hey i would also like to work on the tweet analysis of the text which will be generated from video
> 

Hey, this is already assigned. 
I would be creating more issues, wait till then or I will be adding a way through which you can create issues on your own and assign it to yourself.

**Comment by Pushpita05** [comment]
Hey @hritikksingh Could you gve me some more time like 5-6 days more. I know I am late. Really sorry but was busy with my exams.

**Comment by hritikksingh** [comment]
Sure, you can take 5 more days.
But if you don't complete then I have to reassign.

**Comment by hritikksingh** [comment]
@Pushpita05 any update?

**Comment by Pushpita05** [comment]
trying to complete it. Some tweaks  left with database and therefore issue with validation

**Comment by hritikksingh** [comment]
Alright, keep working.
Tha ks for the update :)
